# Generated by Django 2.2.3 on 2019-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Meal', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Instructions', models.TextField()),
                ('Ingredients', models.TextField()),
            ],
        ),
    ]
