# Generated by Django 2.2.3 on 2019-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Cuisine',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
