# Generated by Django 2.2.3 on 2019-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0005_recipe_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Perishable',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
